USER_NAME := rhruiz
RGBLIGHT_ENABLE = no
BOOTMAGIC_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
RAW_ENABLE = yes
LTO_ENABLE = yes
BOOTLOADER = qmk-dfu

OPT_DEFS += -DPRO_MICRO
