RGBLIGHT_ENABLE = no
BOOTMAGIC_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
RAW_ENABLE = yes
LTO_ENABLE = yes
BOOTLOADER = qmk-dfu
SRC += users/rhruiz/layouts/ortho_5x14.c

OPT_DEFS += -DPRO_MICRO
