name: Unit Tests

permissions:
  contents: read

on:
  push:
    branches:
    - rhruiz

jobs:
  test:
    runs-on: ubuntu-latest

    container: ghcr.io/qmk/qmk_cli

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install dependencies
      run: pip3 install -r requirements-dev.txt
    - name: Run tests
      run: "make $(find tests/users/rhruiz/ -mindepth 1 -maxdepth 1 -type d | rev | cut -d/ -f1 | rev | awk '{ print \"test:\" $1 }' | xargs -n 10 )"
